name: check

on: 
  pull_request:
    branches: [main]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: check
        uses: dagger/dagger-for-github@v7
        with:
          verb: call
          args: check
